services:
  web-eid-asp-dotnet-example:
    image: registry.gitlab.com/web-eid/service/web-eid-authentication-token-validation-dotnet/web-eid-asp-dotnet-example
    restart: always
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your-cert-password
      - OriginUrl=https://localhost:8443
    ports:
      - '127.0.0.1:8443:443'


