name: Dotnet build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x # SDK Version to use.
          
      - name: Cache Nuget packages      
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget
          
      - name: Install dependencies
        run: dotnet restore src/WebEid.Security.sln
        
      - name: Build
        run: dotnet build --configuration Release --no-restore src/WebEid.Security.sln

      - name: Test
        run: dotnet test --no-restore --verbosity normal src/WebEid.Security.sln
